# Generated by Django 3.2.20 on 2023-08-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='remark',
            new_name='remarks',
        ),
    ]
