# Generated by Django 3.2.20 on 2023-08-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='remark',
            new_name='remarks',
        ),
    ]
