# Generated by Django 3.2.20 on 2023-08-27 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('Gaming', 'Gaming'), ('Printing', 'Printing'), ('Assets', 'Assets'), ('Other', 'Other')], max_length=50)),
                ('transaction', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=50)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='business.businesses')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customers.customers')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_detail', to='accounting.transactions')),
            ],
            options={
                'verbose_name_plural': 'Transaction Details',
                'db_table': 'transaction_details',
            },
        ),
        migrations.CreateModel(
            name='GameTimings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_timing', to='accounting.transactions')),
            ],
            options={
                'verbose_name_plural': 'Game Timings',
                'db_table': 'game_timings',
            },
        ),
    ]
