# Generated by Django 3.2.20 on 2023-08-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='remark',
        ),
    ]
