# Generated by Django 3.2.20 on 2023-08-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_transactions_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_status',
            new_name='transaction_types',
        ),
    ]
